Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-060865e8b5914b4c4
Outputs:
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt 'Ec2Instance.AvailabilityZone'
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'Ec2Instance'
  PrivateDNS:
    Description: Private DNSName of the newly created EC2 instance
    Value: !GetAtt 'Ec2Instance.PrivateDnsName'
  PrivateIP:
    Description: Private IP address of the newly created EC2 instance
    Value: !GetAtt 'Ec2Instance.PrivateIp'
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt 'Ec2Instance.PublicDnsName'
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 'Ec2Instance.PublicIp'
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
Resources:
  Ec2Instance:
    Properties:
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI
      InstanceType: t1.micro
      KeyName: !Ref 'KeyName'
      SecurityGroups:
        - default
      UserData: !Base64 '80'
    Type: AWS::EC2::Instance
